defaults:
  - model: admm100
  - metrics: lensless
  - datasets: mirflickr
  - dataloader: main
  - writer: cometml
  - _self_
device: auto
n_log_images: 3
from_pretrained: null

trainer:
  device_tensors: ["lensless", "psf", "lensed"]