defaults:
  - model: admm100
  - metrics: lensless
  - datasets: mirflickr
  - dataloader: main
  - writer: cometml
  - _self_
device: auto
n_log_images: 3

trainer:
  device_tensors: ["lensless", "psf", "lensed"]
  from_pretrained: null